spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: content-topic
          #rocketmq 必须设置
          group: user-topic
        my-input:
          destination: content-my-topic
          #rocketmq 必须设置
          group: my-user-topic
  application:
    name: user-center

server:
  port: 8070

rocketmq:
  name-server: 127.0.0.1:9876

